import Colour from "./colour.js";
export default class Enums {
  Femininity = {
    MASCULINE_STRONG: {
      id: "MASCULINE_STRONG",
      name: "Very Masculine",
      value: 10,
      colour: Colour.MASCULINE,
    },
    MASCULINE: {
      id: "MASCULINE",
      name: "Masculine",
      value: 30,
      colour: Colour.MASCULINE,
    },
    ANDROGYNOUS: {
      id: "ANDROGYNOUS",
      name: "Androgynous",
      value: 50,
      colour: Colour.ANDROGYNOUS,
    },
    FEMININE: {
      id: "FEMININE",
      name: "Feminine",
      value: 70,
      colour: Colour.FEMININE,
    },
    FEMININE_STRONG: {
      id: "FEMININE_STRONG",
      name: "Very Feminine",
      value: 90,
      colour: Colour.FEMININE,
    },
  };

  gender(id, name, hasPenis, hasVagina, hasBreasts, feminine, colour, type) {
    return {
      id: id,
      name: name,
      hasPenis: hasPenis,
      hasVagina: hasVagina,
      hasBreasts: hasBreasts,
      feminine: feminine,
      colour: colour,
      type: type,
    };
  }

  PronounType = {
    MASCULINE: { id: "MASCULINE", name: "masculine", colour: Colour.MASCULINE },
    NEUTRAL: { id: "NEUTRAL", name: "androgynous", colour: Colour.ANDROGYNOUS },
    FEMININE: { id: "FEMININE", name: "feminine", colour: Colour.FEMININE },
  };

  Gender = {
    M_P_V_B_HERMAPHRODITE: this.gender(
      "M_P_V_B_HERMAPHRODITE",
      "hermaphrodite",
      true,
      true,
      true,
      false,
      Colour.MASCULINE,
      "MASCULINE",
    ),
    M_P_V_HERMAPHRODITE: this.gender(
      "M_P_V_HERMAPHRODITE",
      "hermaphrodite",
      true,
      true,
      false,
      false,
      Colour.MASCULINE,
      "MASCULINE",
    ),
    M_P_B_BUSTYBOY: this.gender(
      "M_P_B_BUSTYBOY",
      "bustyboy",
      true,
      false,
      true,
      false,
      Colour.MASCULINE,
      "MASCULINE",
    ),
    M_P_MALE: this.gender(
      "M_P_MALE",
      "male",
      true,
      false,
      false,
      false,
      Colour.MASCULINE,
      "MASCULINE",
    ),
    M_V_B_BUTCH: this.gender(
      "M_V_B_BUTCH",
      "butch",
      false,
      true,
      true,
      false,
      Colour.MASCULINE,
      "MASCULINE",
    ),
    M_V_CUNTBOY: this.gender(
      "M_V_CUNTBOY",
      "cuntboy",
      false,
      true,
      false,
      false,
      Colour.MASCULINE,
      "MASCULINE",
    ),
    M_B_MANNEQUIN: this.gender(
      "M_B_MANNEQUIN",
      "mannequin",
      false,
      false,
      true,
      false,
      Colour.MASCULINE,
      "MASCULINE",
    ),
    M_MANNEQUIN: this.gender(
      "M_MANNEQUIN",
      "mannequin",
      false,
      false,
      false,
      false,
      Colour.MASCULINE,
      "MASCULINE",
    ),
    F_P_V_B_FUTANARI: this.gender(
      "F_P_V_B_FUTANARI",
      "futanari",
      true,
      true,
      true,
      true,
      Colour.FEMININE,
      "FEMININE",
    ),
    F_P_V_FUTANARI: this.gender(
      "F_P_V_FUTANARI",
      "futanari",
      true,
      true,
      false,
      true,
      Colour.FEMININE,
      "FEMININE",
    ),
    F_P_B_SHEMALE: this.gender(
      "F_P_B_SHEMALE",
      "shemale",
      true,
      false,
      true,
      true,
      Colour.FEMININE,
      "FEMININE",
    ),
    F_P_TRAP: this.gender(
      "F_P_TRAP",
      "trap",
      true,
      false,
      false,
      true,
      Colour.FEMININE,
      "FEMININE",
    ),
    F_V_B_FEMALE: this.gender(
      "F_V_B_FEMALE",
      "female",
      false,
      true,
      true,
      true,
      Colour.FEMININE,
      "FEMININE",
    ),
    F_V_FEMALE: this.gender(
      "F_V_FEMALE",
      "female",
      false,
      true,
      false,
      true,
      Colour.FEMININE,
      "FEMININE",
    ),
    F_B_DOLL: this.gender(
      "F_B_DOLL",
      "doll",
      false,
      false,
      true,
      true,
      Colour.FEMININE,
      "FEMININE",
    ),
    F_DOLL: this.gender(
      "F_DOLL",
      "doll",
      false,
      false,
      false,
      true,
      Colour.FEMININE,
      "FEMININE",
    ),
    N_P_V_B_HERMAPHRODITE: this.gender(
      "N_P_V_B_HERMAPHRODITE",
      "hermaphrodite",
      true,
      true,
      true,
      true,
      Colour.ANDROGYNOUS,
      "NEUTRAL",
    ),
    N_P_V_HERMAPHRODITE: this.gender(
      "N_P_V_HERMAPHRODITE",
      "hermaphrodite",
      true,
      true,
      false,
      true,
      Colour.ANDROGYNOUS,
      "NEUTRAL",
    ),
    N_P_B_SHEMALE: this.gender(
      "N_P_B_SHEMALE",
      "shemale",
      true,
      false,
      true,
      true,
      Colour.ANDROGYNOUS,
      "NEUTRAL",
    ),
    N_P_TRAP: this.gender(
      "N_P_TRAP",
      "trap",
      true,
      false,
      false,
      true,
      Colour.ANDROGYNOUS,
      "NEUTRAL",
    ),
    N_V_B_TOMBOY: this.gender(
      "N_V_B_TOMBOY",
      "tomboy",
      false,
      true,
      true,
      true,
      Colour.ANDROGYNOUS,
      "NEUTRAL",
    ),
    N_V_TOMBOY: this.gender(
      "N_V_TOMBOY",
      "tomboy",
      false,
      true,
      false,
      true,
      Colour.ANDROGYNOUS,
      "NEUTRAL",
    ),
    N_B_DOLL: this.gender(
      "N_B_DOLL",
      "doll",
      false,
      false,
      true,
      true,
      Colour.ANDROGYNOUS,
      "NEUTRAL",
    ),
    N_NEUTER: this.gender(
      "N_NEUTER",
      "neuter",
      false,
      false,
      false,
      true,
      Colour.ANDROGYNOUS,
      "NEUTRAL",
    ),
    MALE: M_P_MALE,
    FEMALE: F_V_B_FEMALE,
  };

  Orientation = {
    ANDROPHILIC: {
      id: "ANDROPHILIC",
      name: "androphilic",
      colour: Colour.MASCULINE,
    },
    AMBIPHILIC: {
      id: "AMBIPHILIC",
      name: "ambiphilic",
      colour: Colour.ANDROGYNOUS,
    },
    GYNEPHILIC: {
      id: "GYNEPHILIC",
      name: "gynephilic",
      colour: Colour.FEMININE,
    },
  };

  PERSONALITY = [
    {
      id: "CONFIDENT",
      name: "confident",
      colour: "#b8e36f",
      exclusive: ["SHY"],
    },
    {
      id: "SHY",
      name: "shy",
      colour: Colour.BASE_YELLOW_LIGHT,
      exclusive: ["CONFIDENT"],
    },
    {
      id: "KIND",
      name: "kind",
      colour: Colour.GENERIC_GOOD,
      exclusive: ["SELFISH"],
    },
    {
      id: "SELFISH",
      name: "selfish",
      colour: Colour.GENERIC_BAD,
      exclusive: ["KIND"],
    },
    {
      id: "NAIVE",
      name: "naive",
      colour: Colour.BASE_PINK_LIGHT,
      exclusive: ["CYNICAL"],
    },
    { id: "CYNICAL", name: "cynical", colour: "#8b3a3a", exclusive: ["NAIVE"] },
    { id: "BRAVE", name: "brave", colour: "#e39a6f", exclusive: ["COWARDLY"] },
    {
      id: "COWARDLY",
      name: "cowardly",
      colour: "#e38d8d",
      exclusive: ["BRAVE"],
    },
    {
      id: "LEWD",
      name: "lewd",
      colour: Colour.FEMININE,
      exclusive: ["PRUDE", "INNOCENT"],
    },
    {
      id: "INNOCENT",
      name: "innocent",
      colour: "#6f9be3",
      exclusive: ["LEWD", "PRUDE"],
    },
    {
      id: "PRUDE",
      name: "prude",
      colour: "#6f8aa0",
      exclusive: ["LEWD", "INNOCENT"],
    },
  ];

  MONTHS = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  femininityFromValue = function (n) {
    if (n < 20) return Femininity.MASCULINE_STRONG;
    if (n < 40) return Femininity.MASCULINE;
    if (n < 60) return Femininity.ANDROGYNOUS;
    if (n < 80) return Femininity.FEMININE;
    return Femininity.FEMININE_STRONG;
  };

  article = function (word) {
    return /^[aeiou]/i.test(word) ? "an" : "a";
  };
}
