export default class names {
  HUMAN_NAME_TRIPLETS = [
    ["Alexander", "Alex", "Alexandria"],
    ["Alexius", "Alex", "Alexia"],
    ["Alex", "Alex", "Alex"],
    ["Ash", "Ashe", "Ashley"],
    ["Bart", "Bailey", "Barbara"],
    ["Ben", "Bennie", "Bella"],
    ["Bridger", "Beverly", "Bridget"],
    ["Brian", "Brie", "Brianna"],
    ["Brent", "Brett", "Britta"],
    ["Carey", "Casey", "Cadence"],
    ["Carl", "Carol", "Caroline"],
    ["Cecil", "Cecil", "Cecilia"],
    ["Charlie", "Charlie", "Charlie"],
    ["Chris", "Chris", "Christine"],
    ["Chuck", "Charlie", "Charlotte"],
    ["Daniel", "Danny", "Dani"],
    ["Dale", "Dana", "Diana"],
    ["David", "Deb", "Debbie"],
    ["Dean", "Devin", "Deanna"],
    ["Edward", "Eddie", "Edna"],
    ["Eli", "Emery", "Evelyn"],
    ["Elliot", "Emerson", "Elaine"],
    ["Emmanuel", "Manu", "Emmanuelle"],
    ["Emil", "Em", "Emily"],
    ["Evan", "Evelyn", "Evette"],
    ["Felix", "Flick", "Felicity"],
    ["Frank", "Frankie", "Frances"],
    ["Fred", "Freddie", "Frederica"],
    ["Gabe", "Gabby", "Gale"],
    ["George", "Georgie", "Ginger"],
    ["Greg", "Grey", "Grace"],
    ["Harry", "Harley", "Hailey"],
    ["Henry", "Hennie", "Henrietta"],
    ["Hank", "Hayden", "Holly"],
    ["Ian", "Indigo", "Ilia"],
    ["Isidore", "Izzy", "Isabelle"],
    ["James", "Jamie", "Jaye"],
    ["Jack", "Jackie", "Jacqueline"],
    ["Jensen", "Jackie", "Jasmine"],
    ["Gareth", "Jay", "Jennifer"],
    ["Ian", "Jean", "Jeanne"],
    ["Jerome", "Jerry", "Jeri"],
    ["Jesse", "Jess", "Jessica"],
    ["John", "Jean", "Jane"],
    ["Joseph", "Jojo", "Josie"],
    ["Karl", "Karol", "Karla"],
    ["Kevin", "Kel", "Katie"],
    ["Kasper", "Kat", "Katherine"],
    ["Kenneth", "Kelly", "Kendra"],
    ["Kristopher", "Kris", "Kristie"],
    ["Lawrence", "Loren", "Lauren"],
    ["Lee", "Leigh", "Leah"],
    ["Leonard", "Linden", "Leah"],
    ["Len", "Lumi", "Laura"],
    ["Les", "Lesley", "Leslie"],
    ["Lewis", "Lou", "Louise"],
    ["Madison", "Maddy", "Madeline"],
    ["Mark", "Marion", "Maria"],
    ["Maxwell", "Max", "Maxine"],
    ["Melvin", "Mel", "Melissa"],
    ["Michael", "Micki", "Mikaela"],
    ["Nathan", "Nat", "Natalie"],
    ["Nicholas", "Nicky", "Nicole"],
    ["Norman", "Noble", "Nora"],
    ["Oscar", "Odell", "Opal"],
    ["Oliver", "Oli", "Olivia"],
    ["Pat", "Patsy", "Tricia"],
    ["Page", "Parker", "Paige"],
    ["Peter", "Peyton", "Petra"],
    ["Phillip", "Pip", "Phoebe"],
    ["Quentin", "Quinn", "Quinta"],
    ["Randy", "Randi", "Miranda"],
    ["Richard", "Ricki", "Rachel"],
    ["Robert", "Robbie", "Robyn"],
    ["Samuel", "Sam", "Samantha"],
    ["Stephen", "Steph", "Stephanie"],
    ["Stan", "Sacha", "Summer"],
    ["Terence", "Terry", "Theresa"],
    ["Theodore", "Teddie", "Dora"],
    ["Thomas", "Tommi", "Tamsin"],
    ["Tim", "Temple", "Tina"],
    ["Tracey", "Tracy", "Tessa"],
    ["Tony", "Toni", "Tonya"],
    ["Ulysses", "Umber", "Ursula"],
    ["Valentin", "Val", "Valerie"],
    ["Vin", "Val", "Violet"],
    ["Victor", "Vicky", "Victoria"],
    ["Virgil", "Vic", "Virginia"],
    ["Wallace", "Wallis", "Wanda"],
    ["William", "Winter", "Whitney"],
    ["Will", "Wynne", "Willow"],
    ["Wynn", "Wynne", "Gwen"],
  ];

  HUMAN_SURNAMES = [
    "Adams",
    "Ali",
    "Allen",
    "Anderson",
    "Andrews",
    "Armstrong",
    "Atkinson",
    "Bailey",
    "Baker",
    "Barker",
    "Barnes",
    "Bell",
    "Bennett",
    "Berry",
    "Booth",
    "Bradley",
    "Brooks",
    "Brown",
    "Butler",
    "Campbell",
    "Carr",
    "Carter",
    "Chambers",
    "Chapman",
    "Clark",
    "Clarke",
    "Cole",
    "Collins",
    "Cook",
    "Cooper",
    "Cox",
    "Cunningham",
    "Davies",
    "Davis",
    "Dawson",
    "Dean",
    "Dixon",
    "Edwards",
    "Ellis",
    "Evans",
    "Fisher",
    "Foster",
    "Fox",
    "Gardner",
    "George",
    "Gibson",
    "Gill",
    "Gordon",
    "Graham",
    "Grant",
    "Gray",
    "Green",
    "Griffiths",
    "Hall",
    "Hamilton",
    "Harper",
    "Harris",
    "Harrison",
    "Hart",
    "Harvey",
    "Hill",
    "Holmes",
    "Hudson",
    "Hughes",
    "Hunt",
    "Hunter",
    "Jackson",
    "James",
    "Jenkins",
    "Johnson",
    "Johnston",
    "Jones",
    "Kaur",
    "Kelly",
    "Kennedy",
    "Khan",
    "King",
    "Knight",
    "Lane",
    "Lawrence",
    "Lawson",
    "Lee",
    "Lewis",
    "Lloyd",
    "Macdonald",
    "Marshall",
    "Martin",
    "Mason",
    "Matthews",
    "Mcdonald",
    "Miller",
    "Mills",
    "Mitchell",
    "Moore",
    "Morgan",
    "Morris",
    "Murphy",
    "Murray",
    "Owen",
    "Palmer",
    "Parker",
    "Patel",
    "Pearce",
    "Pearson",
    "Phillips",
    "Poole",
    "Powell",
    "Price",
    "Reid",
    "Reynolds",
    "Richards",
    "Richardson",
    "Roberts",
    "Robertson",
    "Robinson",
    "Rogers",
    "Rose",
    "Ross",
    "Russell",
    "Ryan",
    "Saunders",
    "Scott",
    "Shaw",
    "Simpson",
    "Smith",
    "Spencer",
    "Stevens",
    "Stewart",
    "Stone",
    "Taylor",
    "Thomas",
    "Thompson",
    "Thomson",
    "Turner",
    "Walker",
    "Walsh",
    "Ward",
    "Watson",
    "Watts",
    "Webb",
    "Wells",
    "West",
    "White",
    "Wilkinson",
    "Williams",
    "Williamson",
    "Wilson",
    "Wood",
    "Wright",
    "Young",
  ];

  pick(list) {
    return list[Math.floor(Math.random() * list.length)];
  }

  DEMON_PREFIX_FEM = [
    "Aella",
    "Bella",
    "Cae",
    "Deva",
    "Ella",
    "Fae",
    "Hela",
    "Isa",
    "Katha",
    "Loe",
    "Nysa",
    "Oella",
    "Rae",
    "Sytha",
    "Vixxa",
    "Wynna",
  ];
  DEMON_PREFIX_MAS = ["Ada", "Boro", "Foro", "Helio", "Kiri", "Zara"];
  DEMON_POSTFIX = ["jyx", "ryth", "ney", "nix", "sys", "trix"];

  randomHumanNameTriplet() {
    return pick(LT.HUMAN_NAME_TRIPLETS).slice();
  }

  randomHumanSurname() {
    return pick(HUMAN_SURNAMES);
  }

  randomDemonName(feminine) {
    if (feminine) return pick(DEMON_PREFIX_FEM) + pick(DEMON_POSTFIX);
    return pick(DEMON_PREFIX_MAS) + pick(DEMON_POSTFIX);
  }

  randomOfficialName(opts) {
    opts = opts || {};
    var feminine = !!opts.feminine;
    if (opts.demon) {
      return { name: randomDemonName(feminine), surname: randomHumanSurname() };
    }
    var trip = randomHumanNameTriplet();
    return {
      name: feminine ? trip[2] : trip[0],
      surname: randomHumanSurname(),
    };
  }
}
